name: Build Artifacts

on: push
# on:
#   push:
#     tags:
#       - v*


jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: denolib/setup-deno@v2.3.0

      - run: make all

      - uses: actions/upload-artifact@v1
        with:
          path: dist
          name: caldera
